import { Emoji } from "./types/emoji";
const fs = require("fs");

var list: Emoji[] = [
  {
    label: "🎨",
    description: "Art (improving structure / format of the code)",
    code: ":art:",
  },
  { label: "⚡️", description: "Zap (improving perfomance)", code: ":zap:" },
  { label: "🔥", description: "Fire (removing code or files)", code: ":fire:" },
  { label: "🐛", description: "Bug (fixing a bug)", code: ":bug:" },
  {
    label: "🚑",
    description: "Ambulance (critical hotfix)",
    code: ":ambulance:",
  },
  { label: "✨", description: "Sparkles (new features)", code: ":sparkles:" },
  { label: "📝", description: "Pencil (writing docs)", code: ":pencil:" },
  { label: "🚀", description: "Rocket (deploy)", code: ":rocket:" },
  {
    label: "🙈",
    description: "See no evil (updating .gitignore)",
    code: ":see_no_evil:",
  },
  { label: "💡", description: "Bulb (documenting code)", code: ":bulb:" },
  { label: "💥", description: "Boom (breaking changes)", code: ":boom:" },
  {
    label: "📄",
    description: "Page facing up (updating license)",
    code: ":page_facing_up:",
  },
  {
    label: "🚚",
    description: "Truck (moving or renaming files)",
    code: ":truck:",
  },
  {
    label: "➕",
    description: "Heavy plus sign (adding deps)",
    code: ":heavy_plus_sign:",
  },
  { label: "💯", description: "100", code: ":100:" },
  { label: "🔢", description: "1234", code: ":1234:" },
  { label: "🔔", description: "Bell", code: ":bell:" },
  {
    label: "🎽",
    description: "Running shirt with sash",
    code: ":running_shirt_with_sash:",
  },
  { label: "🌙", description: "Crescent moon", code: ":crescent_moon:" },
  { label: "🔯", description: "Six pointed star", code: ":six_pointed_star:" },
  { label: "🎹", description: "Musical keyboard", code: ":musical_keyboard:" },
  { label: "☝️", description: "Point up", code: ":point_up:" },
  { label: "🕘", description: "Clock9", code: ":clock9:" },
  {
    label: "📉",
    description: "Chart with downwards trend",
    code: ":chart_with_downwards_trend:",
  },
  { label: "😳", description: "Flushed", code: ":flushed:" },
  { label: "🐩", description: "Poodle", code: ":poodle:" },
  { label: "😐", description: "Neutral face", code: ":neutral_face:" },
  { label: "👹", description: "Japanese ogre", code: ":japanese_ogre:" },
  { label: "🐧", description: "Penguin", code: ":penguin:" },
  { label: "↕️", description: "Arrow up down", code: ":arrow_up_down:" },
  { label: "💂", description: "Guardsman", code: ":guardsman:" },
  { label: "🎫", description: "Ticket", code: ":ticket:" },
  { label: "☺️", description: "Relaxed", code: ":relaxed:" },
  { label: "🕛", description: "Clock12", code: ":clock12:" },
  { label: "🐰", description: "Rabbit", code: ":rabbit:" },
  { label: "🐭", description: "Mouse", code: ":mouse:" },
  { label: "😖", description: "Confounded", code: ":confounded:" },
  { label: "⏰", description: "Alarm clock", code: ":alarm_clock:" },
  { label: "👓", description: "Eyeglasses", code: ":eyeglasses:" },
  {
    label: "🔲",
    description: "Black square button",
    code: ":black_square_button:",
  },
  { label: "👧", description: "Girl", code: ":girl:" },
  { label: "💊", description: "Pill", code: ":pill:" },
  { label: "📯", description: "Postal horn", code: ":postal_horn:" },
  { label: "🆓", description: "Free", code: ":free:" },
  {
    label: "😚",
    description: "Kissing closed eyes",
    code: ":kissing_closed_eyes:",
  },
  { label: "⚓️", description: "Anchor", code: ":anchor:" },
  { label: "🐢", description: "Turtle", code: ":turtle:" },
  { label: "🗼", description: "Tokyo tower", code: ":tokyo_tower:" },
  { label: "📏", description: "Straight ruler", code: ":straight_ruler:" },
  { label: "👎", description: "-1", code: ":-1:" },
  { label: "🈺", description: "U55b6", code: ":u55b6:" },
  { label: "🎡", description: "Ferris wheel", code: ":ferris_wheel:" },
  { label: "💌", description: "Love letter", code: ":love_letter:" },
  { label: "🐐", description: "Goat", code: ":goat:" },
  { label: "👘", description: "Kimono", code: ":kimono:" },
  { label: "㊗️", description: "Congratulations", code: ":congratulations:" },
  { label: "🍡", description: "Dango", code: ":dango:" },
  { label: "📑", description: "Bookmark tabs", code: ":bookmark_tabs:" },
  { label: "🐈", description: "Cat2", code: ":cat2:" },
  { label: "🍝", description: "Spaghetti", code: ":spaghetti:" },
  { label: "🚰", description: "Potable water", code: ":potable_water:" },
  { label: "👠", description: "High heel", code: ":high_heel:" },
  { label: "🌎", description: "Earth americas", code: ":earth_americas:" },
  { label: "🚄", description: "Bullettrain side", code: ":bullettrain_side:" },
  { label: "🔡", description: "Abcd", code: ":abcd:" },
  { label: "🎵", description: "Musical note", code: ":musical_note:" },
  { label: "🍥", description: "Fish cake", code: ":fish_cake:" },
  { label: "🐣", description: "Hatching chick", code: ":hatching_chick:" },
  { label: "🚖", description: "Oncoming taxi", code: ":oncoming_taxi:" },
  { label: "💉", description: "Syringe", code: ":syringe:" },
  { label: "💨", description: "Dash", code: ":dash:" },
  { label: "🎠", description: "Carousel horse", code: ":carousel_horse:" },
  { label: "🏣", description: "Post office", code: ":post_office:" },
  { label: "🍸", description: "Cocktail", code: ":cocktail:" },
  {
    label: "👲",
    description: "Man with gua pi mao",
    code: ":man_with_gua_pi_mao:",
  },
  { label: "⁉️", description: "Interrobang", code: ":interrobang:" },
  { label: "💳", description: "Credit card", code: ":credit_card:" },
  { label: "🔕", description: "No bell", code: ":no_bell:" },
  { label: "🎮", description: "Video game", code: ":video_game:" },
  { label: "🍅", description: "Tomato", code: ":tomato:" },
  { label: "5️⃣", description: "Five", code: ":five:" },
  { label: "🐄", description: "Cow2", code: ":cow2:" },
  { label: "🔣", description: "Symbols", code: ":symbols:" },
  { label: "📚", description: "Books", code: ":books:" },
  { label: "💦", description: "Sweat drops", code: ":sweat_drops:" },
  { label: "👶", description: "Baby", code: ":baby:" },
  { label: "♦️", description: "Diamonds", code: ":diamonds:" },
  { label: "⛵️", description: "Sailboat", code: ":sailboat:" },
  { label: "🈵", description: "U6e80", code: ":u6e80:" },
  { label: "💶", description: "Euro", code: ":euro:" },
  { label: "🔃", description: "Arrows clockwise", code: ":arrows_clockwise:" },
  { label: "🚲", description: "Bike", code: ":bike:" },
  { label: "⏩", description: "Fast forward", code: ":fast_forward:" },
  { label: "🔤", description: "Abc", code: ":abc:" },
  { label: "👋", description: "Wave", code: ":wave:" },
  { label: "😮", description: "Open mouth", code: ":open_mouth:" },
  { label: "💍", description: "Ring", code: ":ring:" },
  {
    label: "😥",
    description: "Disappointed relieved",
    code: ":disappointed_relieved:",
  },
  { label: "🔋", description: "Battery", code: ":battery:" },
  { label: "📹", description: "Video camera", code: ":video_camera:" },
  {
    label: "🚛",
    description: "Articulated lorry",
    code: ":articulated_lorry:",
  },
  { label: "♿️", description: "Wheelchair", code: ":wheelchair:" },
  { label: "💧", description: "Droplet", code: ":droplet:" },
  { label: "🍭", description: "Lollipop", code: ":lollipop:" },
  { label: "🍤", description: "Fried shrimp", code: ":fried_shrimp:" },
  { label: "♥️", description: "Hearts", code: ":hearts:" },
  { label: "🍶", description: "Sake", code: ":sake:" },
  { label: "😣", description: "Persevere", code: ":persevere:" },
  { label: "🚓", description: "Police car", code: ":police_car:" },
  { label: "🎦", description: "Cinema", code: ":cinema:" },
  { label: "🏁", description: "Checkered flag", code: ":checkered_flag:" },
  {
    label: "📭",
    description: "Mailbox with no mail",
    code: ":mailbox_with_no_mail:",
  },
  {
    label: "⏳",
    description: "Hourglass flowing sand",
    code: ":hourglass_flowing_sand:",
  },
  { label: "🚭", description: "No smoking", code: ":no_smoking:" },
  {
    label: "➗",
    description: "Heavy division sign",
    code: ":heavy_division_sign:",
  },
  { label: "🚁", description: "Helicopter", code: ":helicopter:" },
  {
    label: "🌔",
    description: "Waxing gibbous moon",
    code: ":waxing_gibbous_moon:",
  },
  { label: "©", description: "Copyright", code: ":copyright:" },
  { label: "📊", description: "Bar chart", code: ":bar_chart:" },
  { label: "🌸", description: "Cherry blossom", code: ":cherry_blossom:" },
  { label: "🍬", description: "Candy", code: ":candy:" },
  { label: "💼", description: "Briefcase", code: ":briefcase:" },
  { label: "📡", description: "Satellite", code: ":satellite:" },
  { label: "🎸", description: "Guitar", code: ":guitar:" },
  { label: "🕜", description: "Clock130", code: ":clock130:" },
  { label: "🔪", description: "Hocho", code: ":hocho:" },
  { label: "🎭", description: "Performing arts", code: ":performing_arts:" },
  { label: "😒", description: "Unamused", code: ":unamused:" },
  { label: "🚐", description: "Minibus", code: ":minibus:" },
  { label: "🐝", description: "Bee", code: ":bee:" },
  { label: "🍦", description: "Icecream", code: ":icecream:" },
  { label: "🚕", description: "Taxi", code: ":taxi:" },
  { label: "🔼", description: "Arrow up small", code: ":arrow_up_small:" },
  { label: "📃", description: "Page with curl", code: ":page_with_curl:" },
  { label: "🔒", description: "Lock", code: ":lock:" },
  { label: "✒️", description: "Black nib", code: ":black_nib:" },
  { label: "👄", description: "Lips", code: ":lips:" },
  { label: "🔩", description: "Nut and bolt", code: ":nut_and_bolt:" },
  { label: "👵", description: "Older woman", code: ":older_woman:" },
  { label: "♑️", description: "Capricorn", code: ":capricorn:" },
  { label: "👎", description: "Thumbsdown", code: ":thumbsdown:" },
  { label: "😧", description: "Anguished", code: ":anguished:" },
  {
    label: "▫️",
    description: "White small square",
    code: ":white_small_square:",
  },
  { label: "🐘", description: "Elephant", code: ":elephant:" },
  { label: "🐍", description: "Snake", code: ":snake:" },
  { label: "💫", description: "Dizzy", code: ":dizzy:" },
  { label: "#️⃣", description: "Hash", code: ":hash:" },
  { label: "™", description: "Tm", code: ":tm:" },
  {
    label: "🔐",
    description: "Closed lock with key",
    code: ":closed_lock_with_key:",
  },
  { label: "🍩", description: "Doughnut", code: ":doughnut:" },
  { label: "👆", description: "Point up 2", code: ":point_up_2:" },
  { label: "🐻", description: "Bear", code: ":bear:" },
  { label: "💣", description: "Bomb", code: ":bomb:" },
  { label: "🌏", description: "Earth asia", code: ":earth_asia:" },
  { label: "🐺", description: "Wolf", code: ":wolf:" },
  { label: "🍵", description: "Tea", code: ":tea:" },
  { label: "📴", description: "Mobile phone off", code: ":mobile_phone_off:" },
  { label: "🚣", description: "Rowboat", code: ":rowboat:" },
  {
    label: "🚵",
    description: "Mountain bicyclist",
    code: ":mountain_bicyclist:",
  },
  { label: "🔂", description: "Repeat one", code: ":repeat_one:" },
  { label: "🎌", description: "Crossed flags", code: ":crossed_flags:" },
  { label: "🍙", description: "Rice ball", code: ":rice_ball:" },
  { label: "🍚", description: "Rice", code: ":rice:" },
  { label: "👽", description: "Alien", code: ":alien:" },
  { label: "🐼", description: "Panda face", code: ":panda_face:" },
  { label: "🈚️", description: "U7121", code: ":u7121:" },
  { label: "📺", description: "Tv", code: ":tv:" },
  { label: "💻", description: "Computer", code: ":computer:" },
  { label: "👺", description: "Japanese goblin", code: ":japanese_goblin:" },
  { label: "🎼", description: "Musical score", code: ":musical_score:" },
  { label: "⌛️", description: "Hourglass", code: ":hourglass:" },
  { label: "🐾", description: "Paw prints", code: ":paw_prints:" },
  { label: "💎", description: "Gem", code: ":gem:" },
  { label: "💭", description: "Thought balloon", code: ":thought_balloon:" },
  { label: "🕠", description: "Clock530", code: ":clock530:" },
  { label: "🍪", description: "Cookie", code: ":cookie:" },
  { label: "🈸", description: "U7533", code: ":u7533:" },
  { label: "🐑", description: "Sheep", code: ":sheep:" },
  { label: "⛪️", description: "Church", code: ":church:" },
  { label: "🈯️", description: "U6307", code: ":u6307:" },
  { label: "🚉", description: "Station", code: ":station:" },
  { label: "🇩🇪", description: "De", code: ":de:" },
  { label: "📒", description: "Ledger", code: ":ledger:" },
  { label: "💬", description: "Speech balloon", code: ":speech_balloon:" },
  { label: "👻", description: "Ghost", code: ":ghost:" },
  { label: "🚫", description: "No entry sign", code: ":no_entry_sign:" },
  { label: "❓", description: "Question", code: ":question:" },
  { label: "😑", description: "Expressionless", code: ":expressionless:" },
  { label: "💟", description: "Heart decoration", code: ":heart_decoration:" },
  { label: "🎻", description: "Violin", code: ":violin:" },
  { label: "♌️", description: "Leo", code: ":leo:" },
  { label: "🔚", description: "End", code: ":end:" },
  {
    label: "🌛",
    description: "First quarter moon with face",
    code: ":first_quarter_moon_with_face:",
  },
  { label: "🕥", description: "Clock1030", code: ":clock1030:" },
  { label: "⚾️", description: "Baseball", code: ":baseball:" },
  {
    label: "🚔",
    description: "Oncoming police car",
    code: ":oncoming_police_car:",
  },
  { label: "📲", description: "Calling", code: ":calling:" },
  {
    label: "😝",
    description: "Stuck out tongue closed eyes",
    code: ":stuck_out_tongue_closed_eyes:",
  },
  { label: "🍃", description: "Leaves", code: ":leaves:" },
  { label: "👑", description: "Crown", code: ":crown:" },
  {
    label: "🔶",
    description: "Large orange diamond",
    code: ":large_orange_diamond:",
  },
  { label: "🌋", description: "Volcano", code: ":volcano:" },
  { label: "💩", description: "Hankey", code: ":hankey:" },
  { label: "😰", description: "Cold sweat", code: ":cold_sweat:" },
  { label: "‼️", description: "Bangbang", code: ":bangbang:" },
  {
    label: "💱",
    description: "Currency exchange",
    code: ":currency_exchange:",
  },
  { label: "😯", description: "Hushed", code: ":hushed:" },
  { label: "⛽️", description: "Fuelpump", code: ":fuelpump:" },
  { label: "🍋", description: "Lemon", code: ":lemon:" },
  { label: "🚻", description: "Restroom", code: ":restroom:" },
  { label: "⚫️", description: "Black circle", code: ":black_circle:" },
  { label: "🔇", description: "Mute", code: ":mute:" },
  { label: "📌", description: "Pushpin", code: ":pushpin:" },
  { label: "😉", description: "Wink", code: ":wink:" },
  { label: "✉️", description: "Envelope", code: ":envelope:" },
  { label: "🍏", description: "Green apple", code: ":green_apple:" },
  { label: "🐹", description: "Hamster", code: ":hamster:" },
  { label: "🍄", description: "Mushroom", code: ":mushroom:" },
  { label: "🚽", description: "Toilet", code: ":toilet:" },
  { label: "🌿", description: "Herb", code: ":herb:" },
  { label: "🕤", description: "Clock930", code: ":clock930:" },
  { label: "🅾", description: "O2", code: ":o2:" },
  { label: "💴", description: "Yen", code: ":yen:" },
  { label: "1️⃣", description: "One", code: ":one:" },
  { label: "🍍", description: "Pineapple", code: ":pineapple:" },
  { label: "🔱", description: "Trident", code: ":trident:" },
  { label: "✂️", description: "Scissors", code: ":scissors:" },
  { label: "🈹", description: "U5272", code: ":u5272:" },
  { label: "📗", description: "Green book", code: ":green_book:" },
  { label: "🌲", description: "Evergreen tree", code: ":evergreen_tree:" },
  { label: "📟", description: "Pager", code: ":pager:" },
  { label: "🎪", description: "Circus tent", code: ":circus_tent:" },
  { label: "👍", description: "Thumbsup", code: ":thumbsup:" },
  { label: "🔑", description: "Key", code: ":key:" },
  { label: "🈷", description: "U6708", code: ":u6708:" },
  { label: "🎿", description: "Ski", code: ":ski:" },
  {
    label: "☑️",
    description: "Ballot box with check",
    code: ":ballot_box_with_check:",
  },
  { label: "🏬", description: "Department store", code: ":department_store:" },
  { label: "🆕", description: "New", code: ":new:" },
  { label: "🐴", description: "Horse", code: ":horse:" },
  { label: "↖️", description: "Arrow upper left", code: ":arrow_upper_left:" },
  { label: "😇", description: "Innocent", code: ":innocent:" },
  { label: "🍑", description: "Peach", code: ":peach:" },
  { label: "🔭", description: "Telescope", code: ":telescope:" },
  { label: "➰", description: "Curly loop", code: ":curly_loop:" },
  { label: "🍞", description: "Bread", code: ":bread:" },
  {
    label: "ℹ️",
    description: "Information source",
    code: ":information_source:",
  },
  { label: "😁", description: "Grin", code: ":grin:" },
  { label: "🔠", description: "Capital abcd", code: ":capital_abcd:" },
  { label: "🎩", description: "Tophat", code: ":tophat:" },
  { label: "🛄", description: "Baggage claim", code: ":baggage_claim:" },
  { label: "👙", description: "Bikini", code: ":bikini:" },
  { label: "🈶", description: "U6709", code: ":u6709:" },
  { label: "🐜", description: "Ant", code: ":ant:" },
  { label: "👉", description: "Point right", code: ":point_right:" },
  { label: "〰", description: "Wavy dash", code: ":wavy_dash:" },
  { label: "♻️", description: "Recycle", code: ":recycle:" },
  { label: "🌍", description: "Earth africa", code: ":earth_africa:" },
  { label: "🎑", description: "Rice scene", code: ":rice_scene:" },
  { label: "◀️", description: "Arrow backward", code: ":arrow_backward:" },
  { label: "🚊", description: "Tram", code: ":tram:" },
  { label: "👡", description: "Sandal", code: ":sandal:" },
  {
    label: "↩️",
    description: "Leftwards arrow with hook",
    code: ":leftwards_arrow_with_hook:",
  },
  { label: "📼", description: "Vhs", code: ":vhs:" },
  { label: "🎢", description: "Roller coaster", code: ":roller_coaster:" },
  { label: "🏧", description: "Atm", code: ":atm:" },
  { label: "🍺", description: "Beer", code: ":beer:" },
  { label: "😷", description: "Mask", code: ":mask:" },
  { label: "👯", description: "Dancers", code: ":dancers:" },
  { label: "🏠", description: "House", code: ":house:" },
  { label: "🏂", description: "Snowboarder", code: ":snowboarder:" },
  { label: "👕", description: "Shirt", code: ":shirt:" },
  { label: "🐝", description: "Honeybee", code: ":honeybee:" },
  { label: "😀", description: "Grinning", code: ":grinning:" },
  { label: "😕", description: "Confused", code: ":confused:" },
  { label: "😤", description: "Triumph", code: ":triumph:" },
  { label: "📙", description: "Orange book", code: ":orange_book:" },
  {
    label: "◽️",
    description: "White medium small square",
    code: ":white_medium_small_square:",
  },
  { label: "🔬", description: "Microscope", code: ":microscope:" },
  { label: "🙏", description: "Pray", code: ":pray:" },
  { label: "🌀", description: "Cyclone", code: ":cyclone:" },
  { label: "🎀", description: "Ribbon", code: ":ribbon:" },
  { label: "🏀", description: "Basketball", code: ":basketball:" },
  { label: "🌟", description: "Star2", code: ":star2:" },
  { label: "🐔", description: "Chicken", code: ":chicken:" },
  { label: "🈳", description: "U7a7a", code: ":u7a7a:" },
  { label: "🏉", description: "Rugby football", code: ":rugby_football:" },
  { label: "📖", description: "Book", code: ":book:" },
  { label: "🌂", description: "Closed umbrella", code: ":closed_umbrella:" },
  { label: "♨️", description: "Hotsprings", code: ":hotsprings:" },
  { label: "😘", description: "Kissing heart", code: ":kissing_heart:" },
  { label: "🚼", description: "Baby symbol", code: ":baby_symbol:" },
  { label: "📜", description: "Scroll", code: ":scroll:" },
  { label: "✏️", description: "Pencil2", code: ":pencil2:" },
  { label: "🚃", description: "Railway car", code: ":railway_car:" },
  { label: "👅", description: "Tongue", code: ":tongue:" },
  { label: "🎉", description: "Tada", code: ":tada:" },
  {
    label: "💠",
    description: "Diamond shape with a dot inside",
    code: ":diamond_shape_with_a_dot_inside:",
  },
  { label: "⬅️", description: "Arrow left", code: ":arrow_left:" },
  {
    label: "🉐",
    description: "Ideograph advantage",
    code: ":ideograph_advantage:",
  },
  { label: "😅", description: "Sweat smile", code: ":sweat_smile:" },
  { label: "💜", description: "Purple heart", code: ":purple_heart:" },
  { label: "🌌", description: "Milky way", code: ":milky_way:" },
  { label: "👝", description: "Pouch", code: ":pouch:" },
  {
    label: "↘️",
    description: "Arrow lower right",
    code: ":arrow_lower_right:",
  },
  { label: "♣️", description: "Clubs", code: ":clubs:" },
  { label: "💞", description: "Revolving hearts", code: ":revolving_hearts:" },
  { label: "🐒", description: "Monkey", code: ":monkey:" },
  { label: "💕", description: "Two hearts", code: ":two_hearts:" },
  { label: "💆", description: "Massage", code: ":massage:" },
  { label: "😨", description: "Fearful", code: ":fearful:" },
  { label: "🙍", description: "Person frowning", code: ":person_frowning:" },
  { label: "🙉", description: "Hear no evil", code: ":hear_no_evil:" },
  {
    label: "🌐",
    description: "Globe with meridians",
    code: ":globe_with_meridians:",
  },
  { label: "🎷", description: "Saxophone", code: ":saxophone:" },
  { label: "🆒", description: "Cool", code: ":cool:" },
  {
    label: "❗️",
    description: "Heavy exclamation mark",
    code: ":heavy_exclamation_mark:",
  },
  { label: "📛", description: "Name badge", code: ":name_badge:" },
  {
    label: "❎",
    description: "Negative squared cross mark",
    code: ":negative_squared_cross_mark:",
  },
  { label: "🐉", description: "Dragon", code: ":dragon:" },
  {
    label: "🔹",
    description: "Small blue diamond",
    code: ":small_blue_diamond:",
  },
  {
    label: "🚘",
    description: "Oncoming automobile",
    code: ":oncoming_automobile:",
  },
  { label: "🏦", description: "Bank", code: ":bank:" },
  { label: "🚾", description: "Wc", code: ":wc:" },
  {
    label: "📔",
    description: "Notebook with decorative cover",
    code: ":notebook_with_decorative_cover:",
  },
  { label: "📮", description: "Postbox", code: ":postbox:" },
  { label: "🍷", description: "Wine glass", code: ":wine_glass:" },
  {
    label: "🌘",
    description: "Waning crescent moon",
    code: ":waning_crescent_moon:",
  },
  { label: "🈂", description: "Sa", code: ":sa:" },
  { label: "✉️", description: "Email", code: ":email:" },
  { label: "🏥", description: "Hospital", code: ":hospital:" },
  { label: "📍", description: "Round pushpin", code: ":round_pushpin:" },
  { label: "🍴", description: "Fork and knife", code: ":fork_and_knife:" },
  { label: "♐️", description: "Sagittarius", code: ":sagittarius:" },
  {
    label: "🚦",
    description: "Vertical traffic light",
    code: ":vertical_traffic_light:",
  },
  {
    label: "🚸",
    description: "Children crossing",
    code: ":children_crossing:",
  },
  { label: "☎️", description: "Phone", code: ":phone:" },
  { label: "🔴", description: "Red circle", code: ":red_circle:" },
  { label: "🍫", description: "Chocolate bar", code: ":chocolate_bar:" },
  { label: "🔓", description: "Unlock", code: ":unlock:" },
  { label: "🔌", description: "Electric plug", code: ":electric_plug:" },
  { label: "🐞", description: "Beetle", code: ":beetle:" },
  { label: "📶", description: "Signal strength", code: ":signal_strength:" },
  { label: "♓️", description: "Pisces", code: ":pisces:" },
  { label: "🚹", description: "Mens", code: ":mens:" },
  { label: "🐸", description: "Frog", code: ":frog:" },
  { label: "🔦", description: "Flashlight", code: ":flashlight:" },
  {
    label: "📬",
    description: "Mailbox with mail",
    code: ":mailbox_with_mail:",
  },
  { label: "😞", description: "Disappointed", code: ":disappointed:" },
  { label: "🛃", description: "Customs", code: ":customs:" },
  { label: "2️⃣", description: "Two", code: ":two:" },
  { label: "🚺", description: "Womens", code: ":womens:" },
  { label: "💥", description: "Collision", code: ":collision:" },
  { label: "⚠️", description: "Warning", code: ":warning:" },
  { label: "💷", description: "Pound", code: ":pound:" },
  { label: "👢", description: "Boot", code: ":boot:" },
  { label: "💖", description: "Sparkling heart", code: ":sparkling_heart:" },
  { label: "🕦", description: "Clock1130", code: ":clock1130:" },
  { label: "🍇", description: "Grapes", code: ":grapes:" },
  { label: "🎾", description: "Tennis", code: ":tennis:" },
  {
    label: "🏤",
    description: "European post office",
    code: ":european_post_office:",
  },
  { label: "🐋", description: "Whale2", code: ":whale2:" },
  { label: "📪", description: "Mailbox closed", code: ":mailbox_closed:" },
  { label: "🐾", description: "Feet", code: ":feet:" },
  { label: "⬇️", description: "Arrow down", code: ":arrow_down:" },
  {
    label: "🏡",
    description: "House with garden",
    code: ":house_with_garden:",
  },
  { label: "🆗", description: "Ok", code: ":ok:" },
  { label: "🕟", description: "Clock430", code: ":clock430:" },
  {
    label: "🗽",
    description: "Statue of liberty",
    code: ":statue_of_liberty:",
  },
  {
    label: "🔏",
    description: "Lock with ink pen",
    code: ":lock_with_ink_pen:",
  },
  { label: "🇬🇧", description: "Gb", code: ":gb:" },
  { label: "🐇", description: "Rabbit2", code: ":rabbit2:" },
  { label: "🔛", description: "On", code: ":on:" },
  { label: "📷", description: "Camera", code: ":camera:" },
  { label: "😺", description: "Smiley cat", code: ":smiley_cat:" },
  { label: "🈁", description: "Koko", code: ":koko:" },
  {
    label: "🌓",
    description: "First quarter moon",
    code: ":first_quarter_moon:",
  },
  {
    label: "🎴",
    description: "Flower playing cards",
    code: ":flower_playing_cards:",
  },
  { label: "✋", description: "Hand", code: ":hand:" },
  { label: "📓", description: "Notebook", code: ":notebook:" },
  { label: "🔉", description: "Sound", code: ":sound:" },
  { label: "☀️", description: "Sunny", code: ":sunny:" },
  { label: "🚪", description: "Door", code: ":door:" },
  { label: "🐌", description: "Snail", code: ":snail:" },
  { label: "🚨", description: "Rotating light", code: ":rotating_light:" },
  { label: "♋️", description: "Cancer", code: ":cancer:" },
  { label: "🏫", description: "School", code: ":school:" },
  { label: "💿", description: "Cd", code: ":cd:" },
  { label: "🍠", description: "Sweet potato", code: ":sweet_potato:" },
  { label: "🏆", description: "Trophy", code: ":trophy:" },
  { label: "🇰🇷", description: "Kr", code: ":kr:" },
  { label: "🌉", description: "Bridge at night", code: ":bridge_at_night:" },
  { label: "🐂", description: "Ox", code: ":ox:" },
  { label: "🚇", description: "Metro", code: ":metro:" },
  { label: "📥", description: "Inbox tray", code: ":inbox_tray:" },
  { label: "🍱", description: "Bento", code: ":bento:" },
  { label: "📣", description: "Mega", code: ":mega:" },
  { label: "😊", description: "Blush", code: ":blush:" },
  { label: "🔙", description: "Back", code: ":back:" },
  { label: "🌑", description: "New moon", code: ":new_moon:" },
  { label: "🌞", description: "Sun with face", code: ":sun_with_face:" },
  { label: "💗", description: "Heartpulse", code: ":heartpulse:" },
  { label: "🆑", description: "Cl", code: ":cl:" },
  { label: "🍯", description: "Honey pot", code: ":honey_pot:" },
  { label: "😪", description: "Sleepy", code: ":sleepy:" },
  { label: "㊙️", description: "Secret", code: ":secret:" },
  { label: "®", description: "Registered", code: ":registered:" },
  { label: "🚧", description: "Construction", code: ":construction:" },
  { label: "🇨🇳", description: "Cn", code: ":cn:" },
  { label: "🎺", description: "Trumpet", code: ":trumpet:" },
  { label: "🍌", description: "Banana", code: ":banana:" },
  { label: "♏️", description: "Scorpius", code: ":scorpius:" },
  { label: "🍂", description: "Fallen leaf", code: ":fallen_leaf:" },
  { label: "🙌", description: "Raised hands", code: ":raised_hands:" },
  {
    label: "〽️",
    description: "Part alternation mark",
    code: ":part_alternation_mark:",
  },
  { label: "🕣", description: "Clock830", code: ":clock830:" },
  { label: "↙️", description: "Arrow lower left", code: ":arrow_lower_left:" },
  {
    label: "🚮",
    description: "Put litter in its place",
    code: ":put_litter_in_its_place:",
  },
  { label: "3️⃣", description: "Three", code: ":three:" },
  { label: "♍️", description: "Virgo", code: ":virgo:" },
  { label: "🐟", description: "Fish", code: ":fish:" },
  { label: "🍓", description: "Strawberry", code: ":strawberry:" },
  { label: "🍐", description: "Pear", code: ":pear:" },
  {
    label: "📞",
    description: "Telephone receiver",
    code: ":telephone_receiver:",
  },
  { label: "😫", description: "Tired face", code: ":tired_face:" },
  { label: "👐", description: "Open hands", code: ":open_hands:" },
  { label: "☁️", description: "Cloud", code: ":cloud:" },
  {
    label: "⏬",
    description: "Arrow double down",
    code: ":arrow_double_down:",
  },
  { label: "🏈", description: "Football", code: ":football:" },
  { label: "💤", description: "Zzz", code: ":zzz:" },
  {
    label: "😙",
    description: "Kissing smiling eyes",
    code: ":kissing_smiling_eyes:",
  },
  { label: "👫", description: "Couple", code: ":couple:" },
  { label: "🚍", description: "Oncoming bus", code: ":oncoming_bus:" },
  { label: "🏨", description: "Hotel", code: ":hotel:" },
  {
    label: "🚅",
    description: "Bullettrain front",
    code: ":bullettrain_front:",
  },
  { label: "👪", description: "Family", code: ":family:" },
  { label: "🐕", description: "Dog2", code: ":dog2:" },
  { label: "🍼", description: "Baby bottle", code: ":baby_bottle:" },
  { label: "🏮", description: "Izakaya lantern", code: ":izakaya_lantern:" },
  { label: "7️⃣", description: "Seven", code: ":seven:" },
  { label: "👟", description: "Athletic shoe", code: ":athletic_shoe:" },
  { label: "😸", description: "Smile cat", code: ":smile_cat:" },
  { label: "📂", description: "Open file folder", code: ":open_file_folder:" },
  { label: "📻", description: "Radio", code: ":radio:" },
  { label: "👍", description: "+1", code: ":+1:" },
  { label: "⤴️", description: "Arrow heading up", code: ":arrow_heading_up:" },
  { label: "🗿", description: "Moyai", code: ":moyai:" },
  { label: "❄️", description: "Snowflake", code: ":snowflake:" },
  { label: "🐨", description: "Koala", code: ":koala:" },
  { label: "😏", description: "Smirk", code: ":smirk:" },
  { label: "🌆", description: "City sunset", code: ":city_sunset:" },
  { label: "🛀", description: "Bath", code: ":bath:" },
  { label: "↔️", description: "Left right arrow", code: ":left_right_arrow:" },
  { label: "🐪", description: "Dromedary camel", code: ":dromedary_camel:" },
  {
    label: "🌝",
    description: "Full moon with face",
    code: ":full_moon_with_face:",
  },
  { label: "⛎", description: "Ophiuchus", code: ":ophiuchus:" },
  {
    label: "🔵",
    description: "Large blue circle",
    code: ":large_blue_circle:",
  },
  { label: "👸", description: "Princess", code: ":princess:" },
  { label: "🎋", description: "Tanabata tree", code: ":tanabata_tree:" },
  { label: "🔨", description: "Hammer", code: ":hammer:" },
  { label: "🐷", description: "Pig", code: ":pig:" },
  { label: "💓", description: "Heartbeat", code: ":heartbeat:" },
  { label: "🏭", description: "Factory", code: ":factory:" },
  { label: "8️⃣", description: "Eight", code: ":eight:" },
  {
    label: "◻️",
    description: "White medium square",
    code: ":white_medium_square:",
  },
  { label: "🗾", description: "Japan", code: ":japan:" },
  { label: "📅", description: "Date", code: ":date:" },
  { label: "🌠", description: "Stars", code: ":stars:" },
  {
    label: "🔸",
    description: "Small orange diamond",
    code: ":small_orange_diamond:",
  },
  { label: "🐶", description: "Dog", code: ":dog:" },
  { label: "🐬", description: "Flipper", code: ":flipper:" },
  { label: "🍈", description: "Melon", code: ":melon:" },
  { label: "🐚", description: "Shell", code: ":shell:" },
  { label: "⛲️", description: "Fountain", code: ":fountain:" },
  { label: "⛺️", description: "Tent", code: ":tent:" },
  { label: "🎬", description: "Clapper", code: ":clapper:" },
  { label: "🌼", description: "Blossom", code: ":blossom:" },
  { label: "🍀", description: "Four leaf clover", code: ":four_leaf_clover:" },
  { label: "👖", description: "Jeans", code: ":jeans:" },
  { label: "🔧", description: "Wrench", code: ":wrench:" },
  { label: "🎊", description: "Confetti ball", code: ":confetti_ball:" },
  { label: "🍻", description: "Beers", code: ":beers:" },
  {
    label: "🚟",
    description: "Suspension railway",
    code: ":suspension_railway:",
  },
  { label: "🎧", description: "Headphones", code: ":headphones:" },
  { label: "💺", description: "Seat", code: ":seat:" },
  { label: "⛅️", description: "Partly sunny", code: ":partly_sunny:" },
  { label: "👚", description: "Womans clothes", code: ":womans_clothes:" },
  { label: "🚙", description: "Blue car", code: ":blue_car:" },
  { label: "🚬", description: "Smoking", code: ":smoking:" },
  {
    label: "👤",
    description: "Bust in silhouette",
    code: ":bust_in_silhouette:",
  },
  { label: "🚎", description: "Trolleybus", code: ":trolleybus:" },
  { label: "🌾", description: "Ear of rice", code: ":ear_of_rice:" },
  { label: "🔟", description: "Keycap ten", code: ":keycap_ten:" },
  { label: "👕", description: "Tshirt", code: ":tshirt:" },
  { label: "🐅", description: "Tiger2", code: ":tiger2:" },
  { label: "😭", description: "Sob", code: ":sob:" },
  { label: "🎍", description: "Bamboo", code: ":bamboo:" },
  { label: "🚴", description: "Bicyclist", code: ":bicyclist:" },
  {
    label: "🔺",
    description: "Small red triangle",
    code: ":small_red_triangle:",
  },
  { label: "🌵", description: "Cactus", code: ":cactus:" },
  { label: "❤️", description: "Heart", code: ":heart:" },
  { label: "🅰", description: "A", code: ":a:" },
  { label: "🅱", description: "B", code: ":b:" },
  { label: "🔊", description: "Loud sound", code: ":loud_sound:" },
  { label: "➿", description: "Loop", code: ":loop:" },
  { label: "✊", description: "Fist", code: ":fist:" },
  { label: "🕧", description: "Clock1230", code: ":clock1230:" },
  { label: "🙋", description: "Raising hand", code: ":raising_hand:" },
  {
    label: "👬",
    description: "Two men holding hands",
    code: ":two_men_holding_hands:",
  },
  { label: "🐙", description: "Octopus", code: ":octopus:" },
  { label: "👈", description: "Point left", code: ":point_left:" },
  { label: "🌔", description: "Moon", code: ":moon:" },
  { label: "👮", description: "Cop", code: ":cop:" },
  { label: "🚏", description: "Busstop", code: ":busstop:" },
  { label: "💵", description: "Dollar", code: ":dollar:" },
  {
    label: "📨",
    description: "Incoming envelope",
    code: ":incoming_envelope:",
  },
  { label: "🚝", description: "Monorail", code: ":monorail:" },
  { label: "💀", description: "Skull", code: ":skull:" },
  { label: "↪️", description: "Arrow right hook", code: ":arrow_right_hook:" },
  { label: "📋", description: "Clipboard", code: ":clipboard:" },
  { label: "🏰", description: "European castle", code: ":european_castle:" },
  { label: "Ⓜ️", description: "M", code: ":m:" },
  { label: "⭕️", description: "O", code: ":o:" },
  { label: "📆", description: "Calendar", code: ":calendar:" },
  { label: "🎇", description: "Sparkler", code: ":sparkler:" },
  { label: "🎲", description: "Game die", code: ":game_die:" },
  { label: "👰", description: "Bride with veil", code: ":bride_with_veil:" },
  { label: "🎆", description: "Fireworks", code: ":fireworks:" },
  { label: "😈", description: "Smiling imp", code: ":smiling_imp:" },
  { label: "🔞", description: "Underage", code: ":underage:" },
  { label: "🎎", description: "Dolls", code: ":dolls:" },
  { label: "👌", description: "Ok hand", code: ":ok_hand:" },
  { label: "🎯", description: "Dart", code: ":dart:" },
  { label: "✌️", description: "V", code: ":v:" },
  { label: "💃", description: "Dancer", code: ":dancer:" },
  { label: "⏪", description: "Rewind", code: ":rewind:" },
  { label: "🔎", description: "Mag right", code: ":mag_right:" },
  { label: "❌", description: "X", code: ":x:" },
  { label: "🙇", description: "Bow", code: ":bow:" },
  { label: "🐮", description: "Cow", code: ":cow:" },
  { label: "😃", description: "Smiley", code: ":smiley:" },
  { label: "👒", description: "Womans hat", code: ":womans_hat:" },
  { label: "🕞", description: "Clock330", code: ":clock330:" },
  { label: "6️⃣", description: "Six", code: ":six:" },
  { label: "🌳", description: "Deciduous tree", code: ":deciduous_tree:" },
  { label: "🍁", description: "Maple leaf", code: ":maple_leaf:" },
  { label: "👦", description: "Boy", code: ":boy:" },
  {
    label: "🔷",
    description: "Large blue diamond",
    code: ":large_blue_diamond:",
  },
  { label: "🐬", description: "Dolphin", code: ":dolphin:" },
  { label: "🎄", description: "Christmas tree", code: ":christmas_tree:" },
  { label: "🅿️", description: "Parking", code: ":parking:" },
  { label: "🆖", description: "Ng", code: ":ng:" },
  { label: "🍣", description: "Sushi", code: ":sushi:" },
  { label: "🎱", description: "8ball", code: ":8ball:" },
  { label: "🆚", description: "Vs", code: ":vs:" },
  { label: "👊", description: "Facepunch", code: ":facepunch:" },
  { label: "⭐️", description: "Star", code: ":star:" },
  { label: "🔖", description: "Bookmark", code: ":bookmark:" },
  { label: "⬆️", description: "Arrow up", code: ":arrow_up:" },
  { label: "🚞", description: "Mountain railway", code: ":mountain_railway:" },
  { label: "🚜", description: "Tractor", code: ":tractor:" },
  { label: "🚯", description: "Do not litter", code: ":do_not_litter:" },
  { label: "🎁", description: "Gift", code: ":gift:" },
  { label: "🍒", description: "Cherries", code: ":cherries:" },
  { label: "🍟", description: "Fries", code: ":fries:" },
  { label: "💾", description: "Floppy disk", code: ":floppy_disk:" },
  { label: "🔝", description: "Top", code: ":top:" },
  { label: "🔫", description: "Gun", code: ":gun:" },
  {
    label: "🌜",
    description: "Last quarter moon with face",
    code: ":last_quarter_moon_with_face:",
  },
  { label: "💪", description: "Muscle", code: ":muscle:" },
  { label: "🍎", description: "Apple", code: ":apple:" },
  { label: "👼", description: "Angel", code: ":angel:" },
  { label: "🍧", description: "Shaved ice", code: ":shaved_ice:" },
  { label: "👴", description: "Older man", code: ":older_man:" },
  { label: "😻", description: "Heart eyes cat", code: ":heart_eyes_cat:" },
  { label: "🚌", description: "Bus", code: ":bus:" },
  { label: "✔️", description: "Heavy check mark", code: ":heavy_check_mark:" },
  { label: "😍", description: "Heart eyes", code: ":heart_eyes:" },
  { label: "🆘", description: "Sos", code: ":sos:" },
  { label: "😂", description: "Joy", code: ":joy:" },
  { label: "🇷🇺", description: "Ru", code: ":ru:" },
  { label: "🏢", description: "Office", code: ":office:" },
  { label: "♊️", description: "Gemini", code: ":gemini:" },
  { label: "😢", description: "Cry", code: ":cry:" },
  {
    label: "🚩",
    description: "Triangular flag on post",
    code: ":triangular_flag_on_post:",
  },
  { label: "🌊", description: "Ocean", code: ":ocean:" },
  { label: "😌", description: "Relieved", code: ":relieved:" },
  { label: "✋", description: "Raised hand", code: ":raised_hand:" },
  { label: "👛", description: "Purse", code: ":purse:" },
  { label: "✅", description: "White check mark", code: ":white_check_mark:" },
  { label: "👃", description: "Nose", code: ":nose:" },
  { label: "🚡", description: "Aerial tramway", code: ":aerial_tramway:" },
  {
    label: "⬛️",
    description: "Black large square",
    code: ":black_large_square:",
  },
  {
    label: "🔀",
    description: "Twisted rightwards arrows",
    code: ":twisted_rightwards_arrows:",
  },
  {
    label: "📈",
    description: "Chart with upwards trend",
    code: ":chart_with_upwards_trend:",
  },
  { label: "📢", description: "Loudspeaker", code: ":loudspeaker:" },
  { label: "👇", description: "Point down", code: ":point_down:" },
  { label: "😆", description: "Laughing", code: ":laughing:" },
  { label: "❇️", description: "Sparkle", code: ":sparkle:" },
  { label: "🚷", description: "No pedestrians", code: ":no_pedestrians:" },
  {
    label: "✴️",
    description: "Eight pointed black star",
    code: ":eight_pointed_black_star:",
  },
  { label: "🕐", description: "Clock1", code: ":clock1:" },
  { label: "4️⃣", description: "Four", code: ":four:" },
  { label: "🎶", description: "Notes", code: ":notes:" },
  { label: "🎤", description: "Microphone", code: ":microphone:" },
  { label: "🇯🇵", description: "Jp", code: ":jp:" },
  { label: "💩", description: "Poop", code: ":poop:" },
  { label: "🐓", description: "Rooster", code: ":rooster:" },
  { label: "🔽", description: "Arrow down small", code: ":arrow_down_small:" },
  { label: "🍛", description: "Curry", code: ":curry:" },
  { label: "🎥", description: "Movie camera", code: ":movie_camera:" },
  { label: "🔈", description: "Speaker", code: ":speaker:" },
  { label: "✈️", description: "Airplane", code: ":airplane:" },
  {
    label: "↗️",
    description: "Arrow upper right",
    code: ":arrow_upper_right:",
  },
  { label: "😟", description: "Worried", code: ":worried:" },
  { label: "🐆", description: "Leopard", code: ":leopard:" },
  { label: "😼", description: "Smirk cat", code: ":smirk_cat:" },
  { label: "🐤", description: "Baby chick", code: ":baby_chick:" },
  {
    label: "😜",
    description: "Stuck out tongue winking eye",
    code: ":stuck_out_tongue_winking_eye:",
  },
  {
    label: "🙎",
    description: "Person with pouting face",
    code: ":person_with_pouting_face:",
  },
  { label: "🍰", description: "Cake", code: ":cake:" },
  { label: "💋", description: "Kiss", code: ":kiss:" },
  {
    label: "◾️",
    description: "Black medium small square",
    code: ":black_medium_small_square:",
  },
  { label: "🌻", description: "Sunflower", code: ":sunflower:" },
  { label: "💔", description: "Broken heart", code: ":broken_heart:" },
  {
    label: "🔻",
    description: "Small red triangle down",
    code: ":small_red_triangle_down:",
  },
  { label: "🕢", description: "Clock730", code: ":clock730:" },
  { label: "🙊", description: "Speak no evil", code: ":speak_no_evil:" },
  { label: "🎏", description: "Flags", code: ":flags:" },
  { label: "🍘", description: "Rice cracker", code: ":rice_cracker:" },
  { label: "💚", description: "Green heart", code: ":green_heart:" },
  { label: "🇫🇷", description: "Fr", code: ":fr:" },
  { label: "😋", description: "Yum", code: ":yum:" },
  { label: "🚶", description: "Walking", code: ":walking:" },
  { label: "😗", description: "Kissing", code: ":kissing:" },
  { label: "🍊", description: "Tangerine", code: ":tangerine:" },
  { label: "🀄️", description: "Mahjong", code: ":mahjong:" },
  { label: "🏮", description: "Lantern", code: ":lantern:" },
  { label: "💰", description: "Moneybag", code: ":moneybag:" },
  { label: "🌇", description: "City sunrise", code: ":city_sunrise:" },
  { label: "💹", description: "Chart", code: ":chart:" },
  { label: "🍉", description: "Watermelon", code: ":watermelon:" },
  { label: "🕑", description: "Clock2", code: ":clock2:" },
  { label: "🏊", description: "Swimmer", code: ":swimmer:" },
  {
    label: "🏪",
    description: "Convenience store",
    code: ":convenience_store:",
  },
  { label: "💈", description: "Barber", code: ":barber:" },
  { label: "💮", description: "White flower", code: ":white_flower:" },
  { label: "🔆", description: "High brightness", code: ":high_brightness:" },
  { label: "♎️", description: "Libra", code: ":libra:" },
  { label: "🎓", description: "Mortar board", code: ":mortar_board:" },
  {
    label: "🌖",
    description: "Waning gibbous moon",
    code: ":waning_gibbous_moon:",
  },
  { label: "💙", description: "Blue heart", code: ":blue_heart:" },
  { label: "🍗", description: "Poultry leg", code: ":poultry_leg:" },
  { label: "😾", description: "Pouting cat", code: ":pouting_cat:" },
  { label: "🐳", description: "Whale", code: ":whale:" },
  { label: "📤", description: "Outbox tray", code: ":outbox_tray:" },
  { label: "😹", description: "Joy cat", code: ":joy_cat:" },
  { label: "🔜", description: "Soon", code: ":soon:" },
  { label: "🌁", description: "Foggy", code: ":foggy:" },
  {
    label: "👱",
    description: "Person with blond hair",
    code: ":person_with_blond_hair:",
  },
  { label: "👾", description: "Space invader", code: ":space_invader:" },
  {
    label: "🔄",
    description: "Arrows counterclockwise",
    code: ":arrows_counterclockwise:",
  },
  { label: "🏄", description: "Surfer", code: ":surfer:" },
  { label: "🍔", description: "Hamburger", code: ":hamburger:" },
  {
    label: "👥",
    description: "Busts in silhouette",
    code: ":busts_in_silhouette:",
  },
  { label: "😶", description: "No mouth", code: ":no_mouth:" },
  { label: "🍆", description: "Eggplant", code: ":eggplant:" },
  {
    label: "🌒",
    description: "Waxing crescent moon",
    code: ":waxing_crescent_moon:",
  },
  { label: "🐖", description: "Pig2", code: ":pig2:" },
  { label: "🕒", description: "Clock3", code: ":clock3:" },
  { label: "🐫", description: "Camel", code: ":camel:" },
  { label: "☕️", description: "Coffee", code: ":coffee:" },
  { label: "🔰", description: "Beginner", code: ":beginner:" },
  { label: "🐁", description: "Mouse2", code: ":mouse2:" },
  {
    label: "◼️",
    description: "Black medium square",
    code: ":black_medium_square:",
  },
  { label: "📕", description: "Closed book", code: ":closed_book:" },
  { label: "⌚️", description: "Watch", code: ":watch:" },
  { label: "⛳️", description: "Golf", code: ":golf:" },
  { label: "💇", description: "Haircut", code: ":haircut:" },
  { label: "🙀", description: "Scream cat", code: ":scream_cat:" },
  { label: "🌹", description: "Rose", code: ":rose:" },
  { label: "🍮", description: "Custard", code: ":custard:" },
  { label: "🚗", description: "Red car", code: ":red_car:" },
  { label: "💢", description: "Anger", code: ":anger:" },
  { label: "⏫", description: "Arrow double up", code: ":arrow_double_up:" },
  { label: "❔", description: "Grey question", code: ":grey_question:" },
  { label: "🍕", description: "Pizza", code: ":pizza:" },
  {
    label: "🔳",
    description: "White square button",
    code: ":white_square_button:",
  },
  {
    label: "🌗",
    description: "Last quarter moon",
    code: ":last_quarter_moon:",
  },
  { label: "😱", description: "Scream", code: ":scream:" },
  { label: "🚤", description: "Speedboat", code: ":speedboat:" },
  { label: "😓", description: "Sweat", code: ":sweat:" },
  { label: "😿", description: "Crying cat face", code: ":crying_cat_face:" },
  {
    label: "✖️",
    description: "Heavy multiplication x",
    code: ":heavy_multiplication_x:",
  },
  { label: "🍨", description: "Ice cream", code: ":ice_cream:" },
  { label: "🔅", description: "Low brightness", code: ":low_brightness:" },
  { label: "😔", description: "Pensive", code: ":pensive:" },
  { label: "🔍", description: "Mag", code: ":mag:" },
  { label: "🐎", description: "Racehorse", code: ":racehorse:" },
  { label: "🚿", description: "Shower", code: ":shower:" },
  { label: "0️⃣", description: "Zero", code: ":zero:" },
  { label: "🚈", description: "Light rail", code: ":light_rail:" },
  { label: "📘", description: "Blue book", code: ":blue_book:" },
  { label: "🃏", description: "Black joker", code: ":black_joker:" },
  {
    label: "💲",
    description: "Heavy dollar sign",
    code: ":heavy_dollar_sign:",
  },
  { label: "⛔️", description: "No entry", code: ":no_entry:" },
  { label: "🕓", description: "Clock4", code: ":clock4:" },
  { label: "🌅", description: "Sunrise", code: ":sunrise:" },
  { label: "🈲", description: "U7981", code: ":u7981:" },
  { label: "🏯", description: "Japanese castle", code: ":japanese_castle:" },
  { label: "👳", description: "Man with turban", code: ":man_with_turban:" },
  { label: "📝", description: "Memo", code: ":memo:" },
  { label: "😲", description: "Astonished", code: ":astonished:" },
  { label: "🌃", description: "Night with stars", code: ":night_with_stars:" },
  { label: "🎈", description: "Balloon", code: ":balloon:" },
  { label: "🐦", description: "Bird", code: ":bird:" },
  { label: "😩", description: "Weary", code: ":weary:" },
  { label: "🙅", description: "No good", code: ":no_good:" },
  { label: "❕", description: "Grey exclamation", code: ":grey_exclamation:" },
  { label: "☔️", description: "Umbrella", code: ":umbrella:" },
  { label: "😆", description: "Satisfied", code: ":satisfied:" },
  { label: "🐥", description: "Hatched chick", code: ":hatched_chick:" },
  { label: "🚗", description: "Car", code: ":car:" },
  { label: "⚪️", description: "White circle", code: ":white_circle:" },
  { label: "🔘", description: "Radio button", code: ":radio_button:" },
  { label: "🍳", description: "Egg", code: ":egg:" },
  {
    label: "✳️",
    description: "Eight spoked asterisk",
    code: ":eight_spoked_asterisk:",
  },
  { label: "💽", description: "Minidisc", code: ":minidisc:" },
  {
    label: "💁",
    description: "Information desk person",
    code: ":information_desk_person:",
  },
  { label: "👂", description: "Ear", code: ":ear:" },
  { label: "🚥", description: "Traffic light", code: ":traffic_light:" },
  { label: "📱", description: "Iphone", code: ":iphone:" },
  { label: "🐱", description: "Cat", code: ":cat:" },
  { label: "🔮", description: "Crystal ball", code: ":crystal_ball:" },
  { label: "🚒", description: "Fire engine", code: ":fire_engine:" },
  { label: "👨", description: "Man", code: ":man:" },
  { label: "🍹", description: "Tropical drink", code: ":tropical_drink:" },
  { label: "♒️", description: "Aquarius", code: ":aquarius:" },
  { label: "👜", description: "Handbag", code: ":handbag:" },
  { label: "👗", description: "Dress", code: ":dress:" },
  { label: "🎳", description: "Bowling", code: ":bowling:" },
  { label: "👀", description: "Eyes", code: ":eyes:" },
  { label: "🚢", description: "Ship", code: ":ship:" },
  { label: "🕔", description: "Clock5", code: ":clock5:" },
  { label: "➡️", description: "Arrow right", code: ":arrow_right:" },
  { label: "😽", description: "Kissing cat", code: ":kissing_cat:" },
  { label: "💸", description: "Money with wings", code: ":money_with_wings:" },
  { label: "🐏", description: "Ram", code: ":ram:" },
  { label: "🍲", description: "Stew", code: ":stew:" },
  { label: "🗻", description: "Mount fuji", code: ":mount_fuji:" },
  {
    label: "🎣",
    description: "Fishing pole and fish",
    code: ":fishing_pole_and_fish:",
  },
  { label: "🔁", description: "Repeat", code: ":repeat:" },
  { label: "😬", description: "Grimacing", code: ":grimacing:" },
  { label: "🕙", description: "Clock10", code: ":clock10:" },
  { label: "📳", description: "Vibration mode", code: ":vibration_mode:" },
  { label: "👞", description: "Mans shoe", code: ":mans_shoe:" },
  { label: "🌈", description: "Rainbow", code: ":rainbow:" },
  { label: "🏩", description: "Love hotel", code: ":love_hotel:" },
  { label: "📠", description: "Fax", code: ":fax:" },
  { label: "▶️", description: "Arrow forward", code: ":arrow_forward:" },
  { label: "🛂", description: "Passport control", code: ":passport_control:" },
  { label: "📐", description: "Triangular ruler", code: ":triangular_ruler:" },
  { label: "💒", description: "Wedding", code: ":wedding:" },
  {
    label: "🌄",
    description: "Sunrise over mountains",
    code: ":sunrise_over_mountains:",
  },
  { label: "👏", description: "Clap", code: ":clap:" },
  { label: "🐯", description: "Tiger", code: ":tiger:" },
  { label: "🐲", description: "Dragon face", code: ":dragon_face:" },
  { label: "📎", description: "Paperclip", code: ":paperclip:" },
  { label: "🎅", description: "Santa", code: ":santa:" },
  { label: "🙆", description: "Ok woman", code: ":ok_woman:" },
  { label: "🐃", description: "Water buffalo", code: ":water_buffalo:" },
  { label: "🕕", description: "Clock6", code: ":clock6:" },
  { label: "💩", description: "Shit", code: ":shit:" },
  { label: "🎒", description: "School satchel", code: ":school_satchel:" },
  { label: "🕝", description: "Clock230", code: ":clock230:" },
  { label: "🐀", description: "Rat", code: ":rat:" },
  { label: "🐗", description: "Boar", code: ":boar:" },
  { label: "🇬🇧", description: "Uk", code: ":uk:" },
  {
    label: "🚠",
    description: "Mountain cableway",
    code: ":mountain_cableway:",
  },
  { label: "😄", description: "Smile", code: ":smile:" },
  { label: "📧", description: "E-mail", code: ":e-mail:" },
  {
    label: "⬜️",
    description: "White large square",
    code: ":white_large_square:",
  },
  { label: "♠️", description: "Spades", code: ":spades:" },
  { label: "🍢", description: "Oden", code: ":oden:" },
  { label: "🌱", description: "Seedling", code: ":seedling:" },
  { label: "☎️", description: "Telephone", code: ":telephone:" },
  { label: "🌺", description: "Hibiscus", code: ":hibiscus:" },
  { label: "📰", description: "Newspaper", code: ":newspaper:" },
  { label: "😛", description: "Stuck out tongue", code: ":stuck_out_tongue:" },
  { label: "👩", description: "Woman", code: ":woman:" },
  { label: "🆙", description: "Up", code: ":up:" },
  { label: "🔪", description: "Knife", code: ":knife:" },
  { label: "📇", description: "Card index", code: ":card_index:" },
  {
    label: "📩",
    description: "Envelope with arrow",
    code: ":envelope_with_arrow:",
  },
  { label: "🐡", description: "Blowfish", code: ":blowfish:" },
  { label: "🛁", description: "Bathtub", code: ":bathtub:" },
  { label: "⛵️", description: "Boat", code: ":boat:" },
  { label: "🎃", description: "Jack o lantern", code: ":jack_o_lantern:" },
  { label: "🏃", description: "Runner", code: ":runner:" },
  { label: "🌰", description: "Chestnut", code: ":chestnut:" },
  { label: "😎", description: "Sunglasses", code: ":sunglasses:" },
  { label: "😠", description: "Angry", code: ":angry:" },
  { label: "💅", description: "Nail care", code: ":nail_care:" },
  { label: "🌴", description: "Palm tree", code: ":palm_tree:" },
  { label: "💛", description: "Yellow heart", code: ":yellow_heart:" },
  { label: "🇺🇸", description: "Us", code: ":us:" },
  { label: "📖", description: "Open book", code: ":open_book:" },
  { label: "💏", description: "Couplekiss", code: ":couplekiss:" },
  { label: "📦", description: "Package", code: ":package:" },
  { label: "🆔", description: "Id", code: ":id:" },
  { label: "📁", description: "File folder", code: ":file_folder:" },
  { label: "♉️", description: "Taurus", code: ":taurus:" },
  {
    label: "💑",
    description: "Couple with heart",
    code: ":couple_with_heart:",
  },
  { label: "🕖", description: "Clock7", code: ":clock7:" },
  { label: "🐠", description: "Tropical fish", code: ":tropical_fish:" },
  { label: "🐊", description: "Crocodile", code: ":crocodile:" },
  { label: "🌕", description: "Full moon", code: ":full_moon:" },
  { label: "😡", description: "Rage", code: ":rage:" },
  { label: "💝", description: "Gift heart", code: ":gift_heart:" },
  { label: "🎰", description: "Slot machine", code: ":slot_machine:" },
  { label: "🐵", description: "Monkey face", code: ":monkey_face:" },
  { label: "🕚", description: "Clock11", code: ":clock11:" },
  {
    label: "👷",
    description: "Construction worker",
    code: ":construction_worker:",
  },
  { label: "👊", description: "Punch", code: ":punch:" },
  { label: "🍜", description: "Ramen", code: ":ramen:" },
  { label: "🈴", description: "U5408", code: ":u5408:" },
  { label: "🎐", description: "Wind chime", code: ":wind_chime:" },
  {
    label: "▪️",
    description: "Black small square",
    code: ":black_small_square:",
  },
  { label: "😴", description: "Sleeping", code: ":sleeping:" },
  { label: "🚋", description: "Train", code: ":train:" },
  { label: "👿", description: "Imp", code: ":imp:" },
  { label: "📀", description: "Dvd", code: ":dvd:" },
  { label: "🚆", description: "Train2", code: ":train2:" },
  { label: "🆎", description: "Ab", code: ":ab:" },
  { label: "🕡", description: "Clock630", code: ":clock630:" },
  { label: "🚂", description: "Steam locomotive", code: ":steam_locomotive:" },
  { label: "📫", description: "Mailbox", code: ":mailbox:" },
  { label: "👞", description: "Shoe", code: ":shoe:" },
  { label: "💄", description: "Lipstick", code: ":lipstick:" },
  { label: "📵", description: "No mobile phones", code: ":no_mobile_phones:" },
  {
    label: "🚱",
    description: "Non-potable water",
    code: ":non-potable_water:",
  },
  { label: "😦", description: "Frowning", code: ":frowning:" },
  { label: "😵", description: "Dizzy face", code: ":dizzy_face:" },
  { label: "👔", description: "Necktie", code: ":necktie:" },
  { label: "♈️", description: "Aries", code: ":aries:" },
  { label: "👣", description: "Footprints", code: ":footprints:" },
  { label: "🕗", description: "Clock8", code: ":clock8:" },
  {
    label: "⤵️",
    description: "Arrow heading down",
    code: ":arrow_heading_down:",
  },
  { label: "➖", description: "Heavy minus sign", code: ":heavy_minus_sign:" },
  { label: "⚽️", description: "Soccer", code: ":soccer:" },
  {
    label: "👭",
    description: "Two women holding hands",
    code: ":two_women_holding_hands:",
  },
  { label: "🇮🇹", description: "It", code: ":it:" },
  { label: "🐽", description: "Pig nose", code: ":pig_nose:" },
  { label: "🌷", description: "Tulip", code: ":tulip:" },
  { label: "❗️", description: "Exclamation", code: ":exclamation:" },
  { label: "9️⃣", description: "Nine", code: ":nine:" },
  { label: "🎂", description: "Birthday", code: ":birthday:" },
  { label: "🛅", description: "Left luggage", code: ":left_luggage:" },
  { label: "🍖", description: "Meat on bone", code: ":meat_on_bone:" },
  { label: "🉑", description: "Accept", code: ":accept:" },
  { label: "🏇", description: "Horse racing", code: ":horse_racing:" },
  { label: "🏃", description: "Running", code: ":running:" },
  { label: "💘", description: "Cupid", code: ":cupid:" },
  { label: "🚳", description: "No bicycles", code: ":no_bicycles:" },
  { label: "🌽", description: "Corn", code: ":corn:" },
  {
    label: "🌚",
    description: "New moon with face",
    code: ":new_moon_with_face:",
  },
  { label: "💐", description: "Bouquet", code: ":bouquet:" },
  { label: "🇪🇸", description: "Es", code: ":es:" },
  { label: "🔗", description: "Link", code: ":link:" },
  { label: "⛄️", description: "Snowman", code: ":snowman:" },
];

export { list };
